export const USER_LOGIN = 'USER_LOGIN';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_ERROR = 'USER_LOGIN_ERROR';

export const USER_REGISTER = 'USER_REGISTER';
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS';
export const USER_REGISTER_ERROR = 'USER_REGISTER_ERROR';

export const USER_CHANGE_PASSWORD = 'USER_CHANGE_PASSWORD';
export const USER_CHANGE_PASSWORD_ERROR = 'USER_CHANGE_PASSWORD_ERROR';

export const SHOW_LOADER = 'SHOW_LOADER';

export const USER_PROFILE_UPDATE = 'USER_PROFILE_UPDATE';
export const USER_PROFILE_UPDATE_ERROR = 'USER_PROFILE_UPDATE_ERROR';

export const USER_FORGOT_PASSWORD = 'USER_FORGOT_PASSWORD';
export const USER_FORGOT_PASSWORD_ERROR = 'USER_FORGOT_PASSWORD_ERROR';
export const UPDATE_AUTH_LOADING = 'UPDATE_AUTH_LOADING';

export const USER_ADD_CHILD = 'USER_ADD_CHILD';
export const USER_ADD_CHILD_SUCCEDED = 'USER_ADD_CHILD_SUCCEDED';
export const USER_ADD_CHILD_FAILED = 'USER_ADD_CHILD_FAILED';

export const USER_ADDCLUB = 'USER_ADDCLUB';
export const USER_ADDCLASS = 'USER_ADDCLASS';
export const USER_ADDSLOT = 'USER_ADDSLOT';

export const USER_GET_CLUB_NAME = 'USER_GET_CLUB_NAME';
export const USER_GET_CLUB_SUCCESS = 'USER_GET_CLUB_SUCCESS';
export const USER_GET_CLUB_FAILED = 'USER_GET_CLUB_FAILED';

export const USER_GET_CLASS_NAME = 'USER_GET_CLASS_NAME';
export const USER_GET_CLASS_SUCCESS = 'USER_GET_CLASS_SUCCESS';
export const USER_GET_CLASS_FAILED = 'USER_GET_CLASS_FAILED';

export const USER_GET_SESSION_LIST = 'USER_GET_SESSION_LIST';
export const USER_GET_SESSION_SUCCESS = 'USER_GET_SESSION_SUCCESS';
export const USER_GET_SESSION_FAILED = 'USER_GET_SESSION_FAILED';

export const USER_GET_POST_CODE = 'USER_GET_POST_CODE';
export const USER_GET_POST_CODE_SUCCESS = 'USER_GET_POST_CODE_SUCCESS';
export const USER_GET_POST_CODE_FAILED = 'USER_GET_POST_CODE_FAILED';

export const USER_POST_CODE_DATA_PASS = 'USER_POST_CODE_DATA_PASS';

export const USER_GET_CLUB_FINANCE = 'USER_GET_CLUB_FINANCE';
export const USER_GET_CLUB_FINANCE_SUCCESS = 'USER_GET_CLUB_FINANCE_SUCCESS';
export const USER_GET_CLUB_FINANCE_FAILED = 'USER_GET_CLUB_FINANCE_FAILED';

export const USER_SET_PROVIDE_CONSENT = 'USER_SET_PROVIDE_CONSENT';

export const USER_SET_ADDITION = 'USER_SET_ADDITION';

export const USER_POST_CONSENT = 'USER_POST_CONSENT';
export const USER_POST_CONSENT_SUCCESS = 'USER_POST_CONSENT_SUCCESS';
export const USER_POST_CONSENT_FAILED = 'USER_POST_CONSENT_FAILED';

export const USER_GET_MEMBER = 'USER_GET_MEMBER';
export const USER_GET_MEMBER_SUCCESS = 'USER_GET_MEMBER_SUCCESS';
export const USER_GET_MEMBER_FAILED = 'USER_GET_MEMBER_FAILED';

export const USER_GET_MEMBER_CLASS_DATA = 'USER_GET_MEMBER_CLASS_DATA';
export const USER_GET_MEMBER_CLASS_DATA_SUCCESS =
  'USER_GET_MEMBER_CLASS_DATA_SUCCESS';
export const USER_GET_MEMBER_CLASS_DATA_FAILED =
  'USER_GET_MEMBER_CLASS_DATA_FAILED';

export const USER_GET_CLASSES = 'USER_CLASSES';
export const USER_GET_CLASSES_SUCCESS = 'USER_CLASSES_SUCCESS';
export const USER_GET_CLASSES_FAILED = 'USER_CLASSES_FAILED';
export const USER_ENROLL_CHILD_SUCCEDED = 'USER_ENROLL_CHILD_SUCCEDED';
export const USER_ENROLL_CHILD_FAILED = 'USER_ENROLL_CHILD_FAILED';
export const USER_ENROLL_CHILD = 'USER_ENROLL_CHILD';

export const USER_GET_CURRENT_MEMBER_DATA = 'USER_GET_CURRENT_MEMBER_DATA';
