export const USER_LOGIN = 'USER_LOGIN';
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_ERROR = 'USER_LOGIN_ERROR';

export const USER_REGISTER = 'USER_REGISTER';
export const USER_REGISTER_SUCCESS = "USER_REGISTER_SUCCESS";
export const USER_REGISTER_ERROR = 'USER_REGISTER_ERROR';

export const USER_CHANGE_PASSWORD = 'USER_CHANGE_PASSWORD';
export const USER_CHANGE_PASSWORD_ERROR = 'USER_CHANGE_PASSWORD_ERROR';

export const SHOW_LOADER = 'SHOW_LOADER';

export const USER_PROFILE_UPDATE = 'USER_PROFILE_UPDATE';
export const USER_PROFILE_UPDATE_ERROR = 'USER_PROFILE_UPDATE_ERROR';

export const USER_FORGOT_PASSWORD = 'USER_FORGOT_PASSWORD';
export const USER_FORGOT_PASSWORD_ERROR = 'USER_FORGOT_PASSWORD_ERROR';
export const UPDATE_AUTH_LOADING = 'UPDATE_AUTH_LOADING';

export const USER_ADDCHILD = "USER_ADDCHILD";
export const USER_ADDCHILD_SUCCESS = "USER_ADDCHILD_SUCCESS";
export const USER_ADDCHILD_FAILED = "USER_ADDCHILD_FAILED";

export const USER_GET_CLUB_NAME = "USER_GET_CLUB_NAME";
export const USER_GET_CLUB_SUCCESS = "USER_GET_CLUB_SUCCESS";
export const USER_GET_CLUB_FAILED = "USER_GET_CLUB_FAILED";

export const USER_GET_CLASS_NAME = "USER_GET_CLASS_NAME";
export const USER_GET_CLASS_SUCCESS = "USER_GET_CLASS_SUCCESS";
export const USER_GET_CLASS_FAILED = "USER_GET_CLASS_FAILED";

export const USER_GET_SESSION_LIST = "USER_GET_SESSION_LIST";
export const USER_GET_SESSION_SUCCESS = "USER_GET_SESSION_SUCCESS";
export const USER_GET_SESSION_FAILED = "USER_GET_SESSION_FAILED";

export const USER_GET_POST_CODE = "USER_GET_POST_CODE";
export const USER_GET_POST_CODE_SUCCESS = "USER_GET_POST_CODE_SUCCESS";
export const USER_GET_POST_CODE_FAILED = "USER_GET_POST_CODE_FAILED";

export const USER_POST_CODE_DATA_PASS = "USER_POST_CODE_DATA_PASS"




